apiVersion: v1
kind: Service
metadata:
  name: watermark-scala
  labels:
    app: watermark-scala
  namespace: local
spec:
  type: NodePort
  ports:
    - port: 8083
      protocol: TCP
      targetPort: 8080
  selector:
    app: watermark-scala